#### 웹 페이지 자동 수집

### 셀레니움

- 웹 브라우저를 자동으로 제어하는 파이썬 라이브러리 (패키지)
- 기능
 
  - 웹페에지 로드 (접속)
  - 입력창에 글자 입력 (아이디 패스워드 등)
  - 버튼 클릭
  - 페이지 이동
  - 화면에 표시 된 텍스트 추출
  - 특정 이미지 저장/ 화면 스크린 캡처
  - 반복 자동화

- 정적인HTML은 Beutifulsoup4, request패키지로 수집가능
- 동적인 웹화면은 selenium이 강력함. 정적인 웹페에지도 가능

#### 웹 브라우저 실행

In [77]:
# 셀레니움 패키지 로드
from selenium import webdriver
import pandas as pd

In [78]:
#웹 브라우저 프로세스를 파이썬이 driver 변수로 관리
driver = webdriver.Chrome()
driver.get('https://www.naver.com')

In [79]:
# 웹 브라우저 종료
driver.quit()

#### 웹페이지 스크래핑 실습

In [80]:
driver = webdriver.Chrome()
driver.get('http://127.0.0.1:5500/chapt%2004/products.html')

#### 요소찾기

- 주요 요소 찾기 방식
  - 'By ID': ID로 찾기
  - 'By CLASS_NAME': class 명으로 찾기
  - 'By TAG_NAME':태그명으로 찾기
  - 'By CSS_SELECTOR': CSS 선택자 방법으로 찾기
  -''By XPATH':Xpath로 찾기

In [81]:
#css 선택자로 요소찾는 함수용 패키지 내 클래스 로드
from selenium.webdriver.common.by import By

In [82]:
# 페이지 내 하나의 데이터만 송출

title = driver.find_element(By.ID,'title')
title.text

'상품목록'

In [83]:
#페이지 내에서 여러 요소를 동시에 추출

products = driver.find_elements(By.CLASS_NAME, 'product')
len(products)

3

In [84]:
products = driver.find_elements(By.CLASS_NAME,'product')

for product in products:
    print(product.text)

키보드 30000
마우스 15000
모니터 250000

#### CSS 선택자로 요소 추출

In [85]:
products = driver.find_elements(By.CSS_SELECTOR, ".product")

for product in products:
    name = product.find_element(By.CSS_SELECTOR, ".name").text
    price = product.find_element(By.CSS_SELECTOR, ".price").text
    print(name, price)

키보드 30000
마우스 15000
모니터 250000

#### 입력창 입력

In [86]:
keyword_input = driver.find_element(By.ID, "keyword")
keyword_input.send_keys("USB")

In [87]:
keyword_input = driver.find_element(By.ID, "keyword")
keyword_input.clear()

In [88]:
keyword_input.send_keys('테슬라')

In [89]:
# 입력태그에서 텍스트 가져오기
keyword_str = driver.find_element(By.ID,'keyword')
keyword_str.get_attribute('value')

'테슬라'

### 버튼클릭

In [90]:
button = driver.find_element(By.ID,'search-btn')
button. click()

#### 명시적 대기

- 링크 클릭으로 다른 페이지 이동, 검색 후 결과 대기까지 시간 소요
- time,sleep(2) '2초동안 대기'등의 파이썬 기본 함수가 제약 사항이 많음
- 특정 조건이 만족할때까지 대기하는 로직 사용

In [91]:
#명시 대기를 위한 패키지 로드

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [93]:
#여러 작업 수행 후

wait = WebDriverWait(driver, 10)

title = wait.until(
    EC.presence_of_element_located((By.ID, 'title'))
)

title.text

'상품목록'

#### 정리

-웹 스크래핑시 필요요소
  웹드라이버로 웹사이트 오픈
  - 필요 요소 찾기
  - 입력태그 찾기
  - 버튼 요소 찾기
  - 입력하고 버튼 클릭해서 동작
  - 데이터 가져오기
  - 화면 갱신될 때까지 명시적 대기

#### 데이터 수집하기

In [127]:
driver.get("http://127.0.0.1:5500/chapt%2004/products.html")

products = driver.find_elements(By.CLASS_NAME, "product")
result = []

for product in products:
    name = product.find_element(By.CLASS_NAME, "name").text
    price = product.find_element(By.CLASS_NAME, "price").text
    result.append({"name": name, "price": price})

In [128]:
result

[{'name': '키보드', 'price': '30000'},
 {'name': '마우스', 'price': '15000'},
 {'name': '모니터', 'price': '250000'}]

In [129]:
df = pd.DataFrame(result)
df

  name   price
0  키보드   30000
1  마우스   15000
2  모니터  250000

In [130]:
df.to_csv ('../data/scrap_products.csv',encoding ='utf-8')

#### 실습

### 멜론 사이트  top100 스크래핑

In [131]:
# 패키지 로드
import pandas as pd
from selenium import webdriver
from selenium. webdriver.common.by import By
from selenium. webdriver. support.ui import WebDriverWait
from selenium. webdriver.support import expected_conditions as EC

In [132]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get("https://www.melon.com/chart/index.htm")

company_name = wait.until(
    EC.presence_of_element_located((By.ID, "footer"))
)

### 차트의 곡 행 가져오기

In [ ]:
#css 선택자 입력시 태그 + .css 동일한 기능
songs= driver.find_elements(By.CSS_SELECTOR,'.lst50,.lst100')
#songs= driver.find_elements(By.CSS_SELECTOR,'tr.lst50, tr.lst100')
len(songs)

for song in songs:

    #노래 순위
    rank = song.find_element(By.CSS_SELECTOR,'.rank').text
    #노래제목
    title = song.find_element(By.CSS_SELECTOR,'.rank01>span>a').text
    #가수
    singer = song.find_element(By.CSS_SELECTOR,'.rank02>a').text
    #앨범
    album = song.find_element(By.CSS_SELECTOR,'.rank03>a').text
    #좋아요 개수
    like = song.find_element(By.CLASS_NAME,'cnt').text

    # print(rank,title,singer,album,like,)
    
    # print(like)
    # print(album)
    # print(singer)
    # print(title)
    # print(rank,title)

In [ ]:
songs= driver.find_elements(By.CSS_SELECTOR,'.lst50,.lst100')
#songs= driver.find_elements(By.CSS_SELECTOR,'tr.lst50, tr.lst100')

datas =[]
#len(songs)

for song in songs:

    #노래 순위
    rank = song.find_element(By.CSS_SELECTOR,'.rank').text
    #노래제목
    title = song.find_element(By.CSS_SELECTOR,'.rank01>span>a').text
    #가수
    singer = song.find_element(By.CSS_SELECTOR,'.rank02>a').text
    #앨범
    album = song.find_element(By.CSS_SELECTOR,'.rank03>a').text
    #좋아요 개수
    like = song.find_element(By.CLASS_NAME,'cnt').text
 
    #단계상승하락
    rank_ud = song.find_element(By.CSS_SELECTOR, ".rank_wrap").get_attribute("title")
   

    datas.append({
        '순위':rank,
        '노래제목':title,
        '가수':singer,
        '앨범':album,
        '좋아요':like,
        '단계상승하락':rank_ud


    })

In [151]:
datas

[{'순위': '1',
  '노래제목': '퇴사할게여 (Narr. 기안84)',
  '가수': '소연 (SOYEON)',
  '앨범': '끝내주는 인생',
  '좋아요': '39,501'},
 {'순위': '2',
  '노래제목': 'LOVE ATTACK',
  '가수': 'RESCENE (리센느)',
  '앨범': 'SCENEDROME',
  '좋아요': '153,133'},
 {'순위': '3',
  '노래제목': '갑자기',
  '가수': '아이오아이 (I.O.I)',
  '앨범': 'I.O.I 3rd MINI ALBUM [I.O.I : LOOP]',
  '좋아요': '80,172'},
 {'순위': '4',
  '노래제목': 'Deja Vu',
  '가수': 'RESCENE (리센느)',
  '앨범': 'Dearest',
  '좋아요': '58,927'},
 {'순위': '5',
  '노래제목': 'Pretty Girl',
  '가수': 'RESCENE (리센느)',
  '앨범': 'Pretty Girl - Special Single',
  '좋아요': '66,154'},
 {'순위': '6',
  '노래제목': 'REDRED',
  '가수': 'CORTIS (코르티스)',
  '앨범': 'GREENGREEN',
  '좋아요': '91,127'},
 {'순위': '7',
  '노래제목': '만찬가',
  '가수': '태연 (TAEYEON)',
  '앨범': 'J-POP REMAKE Vol.1',
  '좋아요': '49,649'},
 {'순위': '8',
  '노래제목': 'BAD',
  '가수': 'ATEEZ(에이티즈)',
  '앨범': 'GOLDEN HOUR : Part.5',
  '좋아요': '33,778'},
 {'순위': '9',
  '노래제목': 'BiiiG',
  '가수': 'BIGBANG (빅뱅)',
  '앨범': 'BiiiG',
  '좋아요': '56,949'},
 {'순위': '10',
  '노래제목': 'LEMONADE',
  '가수': 'aespa',
  '앨범': 'LEMONADE - The 2nd Album',
  '좋아요': '59,586'},
 {'순위': '11',
  '노래제목': 'Drowning',
  '가수': 'WOODZ',
  '앨범': 'OO-LI',
  '좋아요': '309,369'},
 {'순위': '12',
  '노래제목': 'It′s Me',
  '가수': '아일릿(ILLIT)',
  '앨범': 'MAMIHLAPINATAPAI',
  '좋아요': '59,752'},
 {'순위': '13', '노래제목': '이 별로부터', '가수': '아이유', '앨범': '이 별로부터', '좋아요': '31,640'},
 {'순위': '14',
  '노래제목': 'Dear my crazy soulmate',
  '가수': '아이유',
  '앨범': '이 별로부터',
  '좋아요': '28,176'},
 {'순위': '15',
  '노래제목': 'Good Goodbye',
  '가수': '화사 (HWASA)',
  '앨범': 'Good Goodbye',
  '좋아요': '125,781'},
 {'순위': '16',
  '노래제목': '사랑하게 될 거야',
  '가수': '한로로',
  '앨범': '이상비행',
  '좋아요': '149,805'},
 {'순위': '17',
  '노래제목': '노스탈지아',
  '가수': 'BIG Naughty (서동현)',
  '앨범': '노스탈지아',
  '좋아요': '32,567'},
 {'순위': '18',
  '노래제목': 'RUDE!',
  '가수': 'Hearts2Hearts (하츠투하츠)',
  '앨범': 'RUDE!',
  '좋아요': '75,753'},
 {'순위': '19',
  '노래제목': '캐치 캐치',
  '가수': 'YENA (최예나)',
  '앨범': 'LOVE CATCHER',
  '좋아요': '52,060'},
 {'순위': '20',
  '노래제목': '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지',
  '가수': 'AKMU (악뮤)',
  '앨범': '항해',
  '좋아요': '496,820'},
 {'순위': '21',
  '노래제목': '사랑은 늘 도망가',
  '가수': '임영웅',
  '앨범': '신사와 아가씨 OST Part.2',
  '좋아요': '241,228'},
 {'순위': '22',
  '노래제목': 'Popcorn',
  '가수': '도경수(D.O.)',
  '앨범': '성장 - THE 3RD MINI ALBUM',
  '좋아요': '94,926'},
 {'순위': '23', '노래제목': '0+0', '가수': '한로로', '앨범': '자몽살구클럽', '좋아요': '125,729'},
 {'순위': '24',
  '노래제목': '생각을 멈추다 보면',
  '가수': '최유리',
  '앨범': '생각을 멈추다 보면',
  '좋아요': '50,897'},
 {'순위': '25',
  '노래제목': 'Skibidi',
  '가수': "소녀시대-효리수 (Girls' Generation-HRS)",
  '앨범': 'Skibidi',
  '좋아요': '17,099'},
 {'순위': '26', '노래제목': '타임캡슐', '가수': '다비치', '앨범': '타임캡슐', '좋아요': '79,516'},
 {'순위': '27',
  '노래제목': '여름아 부탁해',
  '가수': '볼빨간사춘기',
  '앨범': '여름아 부탁해',
  '좋아요': '29,207'},
 {'순위': '28',
  '노래제목': '기쁨, 슬픔, 아름다운 마음',
  '가수': 'AKMU (악뮤)',
  '앨범': '개화',
  '좋아요': '93,566'},
 {'순위': '29',
  '노래제목': '너의 모든 순간',
  '가수': '성시경',
  '앨범': '별에서 온 그대 OST Part.7',
  '좋아요': '326,958'},
 {'순위': '30',
  '노래제목': '꿈꾸던 어른이 되었나요?',
  '가수': '머무르',
  '앨범': '꿈꾸던 어른이 되었나요?',
  '좋아요': '20,001'},
 {'순위': '31',
  '노래제목': 'Pop Off Pop Off',
  '가수': 'KiiiKiii (키키)',
  '앨범': 'WhyKiiiKiii',
  '좋아요': '23,130'},
 {'순위': '32',
  '노래제목': 'HOME SWEET HOME (feat. 태양, 대성)',
  '가수': 'G-DRAGON',
  '앨범': 'HOME SWEET HOME (feat. 태양, 대성)',
  '좋아요': '234,015'},
 {'순위': '33',
  '노래제목': 'Lemon Tang',
  '가수': 'Hearts2Hearts (하츠투하츠)',
  '앨범': 'Lemon Tang - The 2nd Mini Album',
  '좋아요': '34,195'},
 {'순위': '34',
  '노래제목': '소문의 낙원',
  '가수': 'AKMU (악뮤)',
  '앨범': '개화',
  '좋아요': '90,829'},
 {'순위': '35',
  '노래제목': '어제보다 슬픈 오늘',
  '가수': '우디 (Woody)',
  '앨범': '어제보다 슬픈 오늘',
  '좋아요': '91,176'},
 {'순위': '36',
  '노래제목': '내게 사랑이 뭐냐고 물어본다면',
  '가수': '로이킴',
  '앨범': '내게 사랑이 뭐냐고 물어본다면',
  '좋아요': '102,973'},
 {'순위': '37',
  '노래제목': '404 (New Era)',
  '가수': 'KiiiKiii (키키)',
  '앨범': 'Delulu Pack',
  '좋아요': '73,285'},
 {'순위': '38',
  '노래제목': 'Blue Valentine',
  '가수': 'NMIXX',
  '앨범': 'Blue Valentine',
  '좋아요': '121,637'},
 {'순위': '39',
  '노래제목': '천상연',
  '가수': '이창섭',
  '앨범': "천상연 (웹툰 '선녀외전' X 이창섭 (LEE CHANGSUB))",
  '좋아요': '150,898'},
 {'순위': '40', '노래제목': '또또', '가수': '임영웅', '앨범': 'IM HERO 10', '좋아요': '30,588'},
 {'순위': '41',
  '노래제목': '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))',
  '가수': '너드커넥션 (Nerd Connection)',
  '앨범': '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))',
  '좋아요': '179,558'},
 {'순위': '42',
  '노래제목': 'BANG BANG',
  '가수': 'IVE (아이브)',
  '앨범': 'REVIVE+',
  '좋아요': '69,091'},
 {'순위': '43',
  '노래제목': 'Runaway',
  '가수': 'RESCENE (리센느)',
  '앨범': 'Runaway',
  '좋아요': '35,672'},
 {'순위': '44',
  '노래제목': 'toxic till the end',
  '가수': '로제 (ROSÉ)',
  '앨범': 'rosie',
  '좋아요': '162,240'},
 {'순위': '45',
  '노래제목': '우리들의 블루스',
  '가수': '임영웅',
  '앨범': 'IM HERO',
  '좋아요': '128,617'},
 {'순위': '46',
  '노래제목': '모든 날, 모든 순간 (Every day, Every Moment)',
  '가수': '폴킴',
  '앨범': "'키스 먼저 할까요?' OST Part.3",
  '좋아요': '433,471'},
 {'순위': '47', '노래제목': '멸종위기사랑', '가수': '이찬혁', '앨범': 'EROS', '좋아요': '106,835'},
 {'순위': '48',
  '노래제목': '오늘만 I LOVE YOU',
  '가수': 'BOYNEXTDOOR',
  '앨범': '오늘만 I LOVE YOU',
  '좋아요': '190,827'},
 {'순위': '49',
  '노래제목': '봄 내음보다 너를',
  '가수': '김나영',
  '앨범': '봄 내음보다 너를',
  '좋아요': '142,887'},
 {'순위': '50',
  '노래제목': '한 페이지가 될 수 있게',
  '가수': 'DAY6 (데이식스)',
  '앨범': 'The Book of Us : Gravity',
  '좋아요': '371,540'},
 {'순위': '51',
  '노래제목': '너에게 닿기를',
  '가수': '10CM',
  '앨범': '너에게 닿기를',
  '좋아요': '156,502'},
 {'순위': '52',
  '노래제목': '순간을 영원처럼',
  '가수': '임영웅',
  '앨범': 'IM HERO 2',
  '좋아요': '53,766'},
 {'순위': '53',
  '노래제목': '모르시나요(PROD.로코베리)',
  '가수': '조째즈',
  '앨범': '모르시나요',
  '좋아요': '111,091'},
 {'순위': '54',
  '노래제목': '소나기',
  '가수': '이클립스 (ECLIPSE)',
  '앨범': '선재 업고 튀어 OST Part 1',
  '좋아요': '201,702'},
 {'순위': '55',
  '노래제목': '주저하는 연인들을 위해',
  '가수': '잔나비',
  '앨범': '전설',
  '좋아요': '454,337'},
 {'순위': '56',
  '노래제목': '뛰어(JUMP)',
  '가수': 'BLACKPINK',
  '앨범': '뛰어(JUMP)',
  '좋아요': '100,210'},
 {'순위': '57',
  '노래제목': 'Guitarist',
  '가수': '도경수(D.O.)',
  '앨범': 'DOPAMINE - The 4th Mini Album',
  '좋아요': '16,082'},
 {'순위': '58',
  '노래제목': 'Whiplash',
  '가수': 'aespa',
  '앨범': 'Whiplash - The 5th Mini Album',
  '좋아요': '156,410'},
 {'순위': '59',
  '노래제목': '부디 행복해질 것',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '27,071'},
 {'순위': '60', '노래제목': '청춘만화', '가수': '이무진', '앨범': '만화 (滿花)', '좋아요': '107,812'},
 {'순위': '61',
  '노래제목': 'HAPPY',
  '가수': 'DAY6 (데이식스)',
  '앨범': 'Fourever',
  '좋아요': '218,911'},
 {'순위': '62',
  '노래제목': 'Heavy Serenade',
  '가수': 'NMIXX',
  '앨범': 'Heavy Serenade',
  '좋아요': '56,250'},
 {'순위': '63',
  '노래제목': 'Seven (feat. Latto) - Clean Ver.',
  '가수': '정국',
  '앨범': 'Seven (feat. Latto) - Clean Ver.',
  '좋아요': '233,900'},
 {'순위': '64', '노래제목': 'SWIM', '가수': '방탄소년단', '앨범': 'ARIRANG', '좋아요': '64,572'},
 {'순위': '65',
  '노래제목': '예뻤어',
  '가수': 'DAY6 (데이식스)',
  '앨범': 'Every DAY6 February',
  '좋아요': '381,753'},
 {'순위': '66',
  '노래제목': 'Golden',
  '가수': 'HUNTR/X',
  '앨범': 'KPop Demon Hunters (Soundtrack from the Netflix Film)',
  '좋아요': '193,576'},
 {'순위': '67',
  '노래제목': '이 밤을 빌려 말해요',
  '가수': 'PLAVE',
  '앨범': '이 밤을 빌려 말해요 (오늘 밤, 세계에서 이 사랑이 사라진다 해도 X PLAVE)',
  '좋아요': '34,825'},
 {'순위': '68',
  '노래제목': '그대 작은 나의 세상이 되어',
  '가수': '카더가든',
  '앨범': '부재',
  '좋아요': '88,932'},
 {'순위': '69',
  '노래제목': 'Baila',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '25,836'},
 {'순위': '70',
  '노래제목': 'like JENNIE',
  '가수': '제니 (JENNIE)',
  '앨범': 'Ruby',
  '좋아요': '113,641'},
 {'순위': '71',
  '노래제목': '헤어지자 말해요',
  '가수': '박재정',
  '앨범': '1집 Alone',
  '좋아요': '196,436'},
 {'순위': '72', '노래제목': '모이세', '가수': '임영웅', '앨범': 'IM HERO 10', '좋아요': '26,640'},
 {'순위': '73',
  '노래제목': 'Love wins all',
  '가수': '아이유',
  '앨범': 'The Winning',
  '좋아요': '226,755'},
 {'순위': '74',
  '노래제목': 'Dynamite',
  '가수': '방탄소년단',
  '앨범': 'Dynamite (DayTime Version)',
  '좋아요': '460,581'},
 {'순위': '75', '노래제목': '입춘', '가수': '한로로', '앨범': '입춘', '좋아요': '85,133'},
 {'순위': '76',
  '노래제목': 'Die With A Smile',
  '가수': 'Lady Gaga',
  '앨범': 'Die With A Smile',
  '좋아요': '142,470'},
 {'순위': '77',
  '노래제목': '살아온 우리에게',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '24,789'},
 {'순위': '78', '노래제목': '나는 반딧불', '가수': '황가람', '앨범': '나는 반딧불', '좋아요': '160,832'},
 {'순위': '79',
  '노래제목': 'Welcome to the Show',
  '가수': 'DAY6 (데이식스)',
  '앨범': 'Fourever',
  '좋아요': '203,299'},
 {'순위': '80',
  '노래제목': '사랑인가 봐',
  '가수': '멜로망스',
  '앨범': '사랑인가 봐 (사내맞선 OST 스페셜 트랙)',
  '좋아요': '240,127'},
 {'순위': '81',
  '노래제목': '봄날',
  '가수': '방탄소년단',
  '앨범': 'YOU NEVER WALK ALONE',
  '좋아요': '501,265'},
 {'순위': '82',
  '노래제목': '첫 만남은 계획대로 되지 않아',
  '가수': 'TWS (투어스)',
  '앨범': 'Sparkling Blue',
  '좋아요': '177,375'},
 {'순위': '83',
  '노래제목': '미워요 RE',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '24,343'},
 {'순위': '84',
  '노래제목': 'APT.',
  '가수': '로제 (ROSÉ)',
  '앨범': 'APT.',
  '좋아요': '222,606'},
 {'순위': '85',
  '노래제목': 'Vitamin ME',
  '가수': '프로미스나인',
  '앨범': 'Glow ME',
  '좋아요': '20,254'},
 {'순위': '86',
  '노래제목': '청혼하지 않을 이유를 못 찾았어',
  '가수': '이무진',
  '앨범': '청혼하지 않을 이유를 못 찾았어',
  '좋아요': '77,966'},
 {'순위': '87',
  '노래제목': '다정히 내 이름을 부르면',
  '가수': '경서예지',
  '앨범': '다정히 내 이름을 부르면 (경서예지 x 전건호)',
  '좋아요': '225,993'},
 {'순위': '88',
  '노래제목': 'Hype Boy',
  '가수': 'NewJeans',
  '앨범': "NewJeans 1st EP 'New Jeans'",
  '좋아요': '318,220'},
 {'순위': '89',
  '노래제목': '모래 알갱이 RE',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '23,976'},
 {'순위': '90',
  '노래제목': 'STYLE',
  '가수': 'Hearts2Hearts (하츠투하츠)',
  '앨범': 'STYLE',
  '좋아요': '66,842'},
 {'순위': '91',
  '노래제목': 'Magnetic',
  '가수': '아일릿(ILLIT)',
  '앨범': 'SUPER REAL ME',
  '좋아요': '149,307'},
 {'순위': '92',
  '노래제목': 'CRASH',
  '가수': 'ALLDAY PROJECT',
  '앨범': 'CRASH',
  '좋아요': '5,203'},
 {'순위': '93',
  '노래제목': 'Love Love Love (Feat. Yoong Jin Of Casker)',
  '가수': '에픽하이 (EPIK HIGH)',
  '앨범': 'Remapping The Human Soul',
  '좋아요': '129,853'},
 {'순위': '94',
  '노래제목': '사랑은 늘 도망가 RE',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '23,781'},
 {'순위': '95',
  '노래제목': 'A Bientot RE',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '23,761'},
 {'순위': '96',
  '노래제목': 'Less than a Lover',
  '가수': '제니 (JENNIE)',
  '앨범': 'Less than a Lover',
  '좋아요': '27,096'},
 {'순위': '97',
  '노래제목': 'New York',
  '가수': '임영웅',
  '앨범': 'IM HERO 10',
  '좋아요': '24,265'},
 {'순위': '98',
  '노래제목': '그댈 위한 멜로디',
  '가수': '임영웅',
  '앨범': 'IM HERO 2',
  '좋아요': '42,732'},
 {'순위': '99',
  '노래제목': '사랑은 봄비처럼...이별은 겨울비처럼...',
  '가수': '임현정',
  '앨범': 'All That Love',
  '좋아요': '76,460'},
 {'순위': '100',
  '노래제목': 'REBEL HEART',
  '가수': 'IVE (아이브)',
  '앨범': 'IVE EMPATHY',
  '좋아요': '122,857'}]

In [169]:
driver.quit()

In [152]:
df_melon100=pd.DataFrame(datas)
df_melon100

,순위,노래제목,가수,앨범,좋아요
0,1,퇴사할게여 (Narr. 기안84),소연 (SOYEON),끝내주는 인생,"39,501"
1,2,LOVE ATTACK,RESCENE (리센느),SCENEDROME,"153,133"
2,3,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],"80,172"
3,4,Deja Vu,RESCENE (리센느),Dearest,"58,927"
4,5,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,"66,154"
...,...,...,...,...,...
95,96,Less than a Lover,제니 (JENNIE),Less than a Lover,"27,096"
96,97,New York,임영웅,IM HERO 10,"24,265"
97,98,그댈 위한 멜로디,임영웅,IM HERO 2,"42,732"
98,99,사랑은 봄비처럼...이별은 겨울비처럼...,임현정,All That Love,"76,460"
99,100,REBEL HEART,IVE (아이브),IVE EMPATHY,"122,857"

In [172]:
df_melon100.to_csv('../data/멜론100_261001.csv',encoding='utf-8')